# denotes branch mapping
branch:
  # denotes the site name, only one unique site name is allowed
  example.com:
    hostname: example.com  # denotes the hostname of the server hosting the site
    user: example-user
    deploy_path: /path/to/bench
    prev_releases_limit: 10 
    apps_paths: 
      - some_app
      - some_dir/another_app
    submodule_apps_path:
      - some_submodule_app
      - some_dir/some_submodule_app

# Can have more than one sites per branch
another-branch:
  some.domain:
    hostname: another.domain
    user: some-username
    deploy_path: /path/to/bench
    prev_releases_limit: 10
    # Since `apps_paths` is not provided, the action will assume that the app is the repository itself
  another.domain:
    # ...
    # You can add more than one site for a single branch.