name: "Deploy Frappe"
description: "Deploy Frappe code to a server"
author: "rtCamp"
outputs:
  out:
    description: output
runs:
  using: "docker"
  #image: "Dockerfile"
  image: 'docker://ghcr.io/rtcamp/action_deploy_frappe:0.0.1'

branding:
  icon: "upload-cloud"
  color: "yellow"
